name: Flutter_Android_Build_And_Test

on:
  push:
    branches: [main]

jobs:
  flutter_test:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: '11'
        - uses: subosito/flutter-action@v1
          with:
            flutter-version: '2.10.5'

        - name: Get all Flutter Packages
          run: flutter pub get

        - name: Run Flutter Test
          run: flutter test
    
  build_android:
    needs: flutter_test
    runs-on: ubuntu-latest
      

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Setup Java to compile Android project
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.5'

      - name: Create the Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          # import keystore from secrets
          echo $KEYSTORE_BASE64 | base64 -di > $RUNNER_TEMP/my_production.keystore

      - name: Clean packages
        run: flutter clean
      
      - name: Restore packages
        run: flutter pub get
      
      - name: Build Android App Bundle
        run: flutter build appbundle --release


      - name: Sign AAB
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: build/app/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEYSTORE_PASSWORD_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Publish Android Artefacts
        uses: actions/upload-artifact@v1
        with:
          name: release-aab-signed
          path: build/app/outputs/bundle/release/app-release.aab  